import { getSiteSettings } from "@/lib/site";
import { PageHeader } from "@/components/admin/PageHeader";
import { SettingsForm } from "./SettingsForm";

export const dynamic = "force-dynamic";
export const metadata = { title: "Ayarlar", robots: { index: false } };

export default async function SettingsPage() {
  const settings = await getSiteSettings();
  return (
    <div className="space-y-6">
      <PageHeader
        title="Site Ayarları"
        description="Logo, iletişim bilgileri, sosyal medya, SEO varsayılanları."
      />
      <SettingsForm
        initial={{
          siteName: settings.siteName,
          logoUrl: settings.logoUrl ?? "",
          faviconUrl: settings.faviconUrl ?? "",
          tagline: settings.tagline ?? "",
          email: settings.email ?? "",
          phone: settings.phone ?? "",
          address: settings.address ?? "",
          whatsapp: settings.whatsapp ?? "",
          linkedinUrl: settings.linkedinUrl ?? "",
          instagramUrl: settings.instagramUrl ?? "",
          xUrl: settings.xUrl ?? "",
          footerText: settings.footerText ?? "",
          defaultSeoTitle: settings.defaultSeoTitle ?? "",
          defaultSeoDesc: settings.defaultSeoDesc ?? "",
          gtmId: settings.gtmId ?? "",
          statProjects: settings.statProjects,
          statSectors: settings.statSectors,
          statYears: settings.statYears,
          statEndUsers: settings.statEndUsers,
          teamSize: settings.teamSize,
          foundedYear: settings.foundedYear,
          heroHeading: settings.heroHeading ?? "",
          heroHighlight: settings.heroHighlight ?? "",
          heroSubtitle: settings.heroSubtitle ?? "",
          heroStatusText: settings.heroStatusText ?? "",
          heroImageUrl: settings.heroImageUrl ?? "",
          careersHeading: settings.careersHeading ?? "",
          careersLead: settings.careersLead ?? "",
          careersImage: settings.careersImage ?? "",
          contactHeading: settings.contactHeading ?? "",
          contactHighlight: settings.contactHighlight ?? "",
          contactLead: settings.contactLead ?? "",
          officeHours: settings.officeHours ?? "",
          heroCtaPrimaryLabel: settings.heroCtaPrimaryLabel ?? "",
          heroCtaPrimaryUrl: settings.heroCtaPrimaryUrl ?? "",
          heroCtaSecondaryLabel: settings.heroCtaSecondaryLabel ?? "",
          heroCtaSecondaryUrl: settings.heroCtaSecondaryUrl ?? "",
          heroOverlayLabel: settings.heroOverlayLabel ?? "",
          heroOverlayTitle: settings.heroOverlayTitle ?? "",
          heroOverlayDescription: settings.heroOverlayDescription ?? "",
          careersEmptyTitle: settings.careersEmptyTitle ?? "",
          careersEmptyText: settings.careersEmptyText ?? "",
          careersApplyLabel: settings.careersApplyLabel ?? "",
          projectsEyebrow: settings.projectsEyebrow ?? "",
          projectsTitle: settings.projectsTitle ?? "",
          projectsLead: settings.projectsLead ?? "",
          sectorsEyebrow: settings.sectorsEyebrow ?? "",
          sectorsTitle: settings.sectorsTitle ?? "",
          sectorsLead: settings.sectorsLead ?? "",
          blogEyebrow: settings.blogEyebrow ?? "",
          blogTitle: settings.blogTitle ?? "",
          blogLead: settings.blogLead ?? "",
          navBrandsLabel: settings.navBrandsLabel ?? "",
          navSectorsLabel: settings.navSectorsLabel ?? "",
          navBlogLabel: settings.navBlogLabel ?? "",
          navCareersLabel: settings.navCareersLabel ?? "",
          navContactLabel: settings.navContactLabel ?? "",
          headerCtaLabel: settings.headerCtaLabel ?? "",
          heroImageLabel: settings.heroImageLabel ?? "",
          heroStatProjectsLabel: settings.heroStatProjectsLabel ?? "",
          heroStatSectorsLabel: settings.heroStatSectorsLabel ?? "",
          heroStatUsersLabel: settings.heroStatUsersLabel ?? "",
          brandsFilterAllLabel: settings.brandsFilterAllLabel ?? "",
          brandsCountSingular: settings.brandsCountSingular ?? "",
          brandsCountPlural: settings.brandsCountPlural ?? "",
          brandCardCtaLabel: settings.brandCardCtaLabel ?? "",
          brandCardExternalLabel: settings.brandCardExternalLabel ?? "",
          brandCardMetaPrefix: settings.brandCardMetaPrefix ?? "",
          brandCardPendingLabel: settings.brandCardPendingLabel ?? "",
          blogReadFullLabel: settings.blogReadFullLabel ?? "",
          blogReadLabel: settings.blogReadLabel ?? "",
          blogAllPostsLabel: settings.blogAllPostsLabel ?? "",
          blogFeaturedImageLabel: settings.blogFeaturedImageLabel ?? "",
          careersEyebrow: settings.careersEyebrow ?? "",
          careersOpenPositionsLabel: settings.careersOpenPositionsLabel ?? "",
          careersImageLabel: settings.careersImageLabel ?? "",
          contactEyebrow: settings.contactEyebrow ?? "",
          contactEmailLabel: settings.contactEmailLabel ?? "",
          contactPhoneLabel: settings.contactPhoneLabel ?? "",
          contactOfficeLabel: settings.contactOfficeLabel ?? "",
          contactHoursLabel: settings.contactHoursLabel ?? "",
          contactFormTitle: settings.contactFormTitle ?? "",
          contactNameLabel: settings.contactNameLabel ?? "",
          contactNamePlaceholder: settings.contactNamePlaceholder ?? "",
          contactEmailFieldLabel: settings.contactEmailFieldLabel ?? "",
          contactEmailPlaceholder: settings.contactEmailPlaceholder ?? "",
          contactCompanyLabel: settings.contactCompanyLabel ?? "",
          contactCompanyPlaceholder: settings.contactCompanyPlaceholder ?? "",
          contactMessageLabel: settings.contactMessageLabel ?? "",
          contactMessagePlaceholder: settings.contactMessagePlaceholder ?? "",
          contactSubmitLabel: settings.contactSubmitLabel ?? "",
          contactSendingLabel: settings.contactSendingLabel ?? "",
          contactSuccessLabel: settings.contactSuccessLabel ?? "",
          contactPrivacyText: settings.contactPrivacyText ?? "",
          contactSubject: settings.contactSubject ?? "",
          footerCompanyHeading: settings.footerCompanyHeading ?? "",
          footerBrandsHeading: settings.footerBrandsHeading ?? "",
          footerContactHeading: settings.footerContactHeading ?? "",
          footerAboutLabel: settings.footerAboutLabel ?? "",
          footerCopyrightSuffix: settings.footerCopyrightSuffix ?? "",
          footerKvkkLabel: settings.footerKvkkLabel ?? "",
          footerPrivacyLabel: settings.footerPrivacyLabel ?? "",
          footerCookiesLabel: settings.footerCookiesLabel ?? "",
        }}
      />
    </div>
  );
}
