"use server";

import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/db";
import { settingsUpdateSchema } from "@/lib/validators/settings";
import { requireAdmin } from "./_helpers";

export async function updateSettings(input: unknown) {
  await requireAdmin();
  const parsed = settingsUpdateSchema.parse(input);

  const data = {
    siteName: parsed.siteName,
    logoUrl: parsed.logoUrl || null,
    faviconUrl: parsed.faviconUrl || null,
    tagline: parsed.tagline || null,
    email: parsed.email || null,
    phone: parsed.phone || null,
    address: parsed.address || null,
    whatsapp: parsed.whatsapp || null,
    linkedinUrl: parsed.linkedinUrl || null,
    instagramUrl: parsed.instagramUrl || null,
    xUrl: parsed.xUrl || null,
    footerText: parsed.footerText || null,
    defaultSeoTitle: parsed.defaultSeoTitle || null,
    defaultSeoDesc: parsed.defaultSeoDesc || null,
    gtmId: parsed.gtmId || null,
    statProjects: parsed.statProjects ?? 13,
    statSectors: parsed.statSectors ?? 6,
    statYears: parsed.statYears ?? 10,
    statEndUsers: parsed.statEndUsers || "120K",
    teamSize: parsed.teamSize ?? 38,
    foundedYear: parsed.foundedYear ?? 2014,
    heroHeading: parsed.heroHeading || null,
    heroHighlight: parsed.heroHighlight || null,
    heroSubtitle: parsed.heroSubtitle || null,
    heroStatusText: parsed.heroStatusText || null,
    heroImageUrl: parsed.heroImageUrl || null,
    aboutHeading: parsed.aboutHeading || null,
    aboutLead: parsed.aboutLead || null,
    aboutImage1: parsed.aboutImage1 || null,
    aboutImage2: parsed.aboutImage2 || null,
    aboutImage3: parsed.aboutImage3 || null,
    careersHeading: parsed.careersHeading || null,
    careersLead: parsed.careersLead || null,
    careersImage: parsed.careersImage || null,
    contactHeading: parsed.contactHeading || null,
    contactHighlight: parsed.contactHighlight || null,
    contactLead: parsed.contactLead || null,
    officeHours: parsed.officeHours || null,
    heroCtaPrimaryLabel: parsed.heroCtaPrimaryLabel || null,
    heroCtaPrimaryUrl: parsed.heroCtaPrimaryUrl || null,
    heroCtaSecondaryLabel: parsed.heroCtaSecondaryLabel || null,
    heroCtaSecondaryUrl: parsed.heroCtaSecondaryUrl || null,
    heroOverlayLabel: parsed.heroOverlayLabel || null,
    heroOverlayTitle: parsed.heroOverlayTitle || null,
    heroOverlayDescription: parsed.heroOverlayDescription || null,
    careersEmptyTitle: parsed.careersEmptyTitle || null,
    careersEmptyText: parsed.careersEmptyText || null,
    careersApplyLabel: parsed.careersApplyLabel || null,
    projectsEyebrow: parsed.projectsEyebrow || null,
    projectsTitle: parsed.projectsTitle || null,
    projectsLead: parsed.projectsLead || null,
    sectorsEyebrow: parsed.sectorsEyebrow || null,
    sectorsTitle: parsed.sectorsTitle || null,
    sectorsLead: parsed.sectorsLead || null,
    clientsEyebrow: parsed.clientsEyebrow || null,
    clientsTitle: parsed.clientsTitle || null,
    clientsLead: parsed.clientsLead || null,
    blogEyebrow: parsed.blogEyebrow || null,
    blogTitle: parsed.blogTitle || null,
    blogLead: parsed.blogLead || null,
    navBrandsLabel: parsed.navBrandsLabel || null,
    navSectorsLabel: parsed.navSectorsLabel || null,
    navBlogLabel: parsed.navBlogLabel || null,
    navCareersLabel: parsed.navCareersLabel || null,
    navContactLabel: parsed.navContactLabel || null,
    headerCtaLabel: parsed.headerCtaLabel || null,
    heroImageLabel: parsed.heroImageLabel || null,
    heroStatProjectsLabel: parsed.heroStatProjectsLabel || null,
    heroStatSectorsLabel: parsed.heroStatSectorsLabel || null,
    heroStatUsersLabel: parsed.heroStatUsersLabel || null,
    brandsFilterAllLabel: parsed.brandsFilterAllLabel || null,
    brandsCountSingular: parsed.brandsCountSingular || null,
    brandsCountPlural: parsed.brandsCountPlural || null,
    brandCardCtaLabel: parsed.brandCardCtaLabel || null,
    brandCardExternalLabel: parsed.brandCardExternalLabel || null,
    brandCardMetaPrefix: parsed.brandCardMetaPrefix || null,
    brandCardPendingLabel: parsed.brandCardPendingLabel || null,
    blogReadFullLabel: parsed.blogReadFullLabel || null,
    blogReadLabel: parsed.blogReadLabel || null,
    blogAllPostsLabel: parsed.blogAllPostsLabel || null,
    blogFeaturedImageLabel: parsed.blogFeaturedImageLabel || null,
    careersEyebrow: parsed.careersEyebrow || null,
    careersOpenPositionsLabel: parsed.careersOpenPositionsLabel || null,
    careersImageLabel: parsed.careersImageLabel || null,
    contactEyebrow: parsed.contactEyebrow || null,
    contactEmailLabel: parsed.contactEmailLabel || null,
    contactPhoneLabel: parsed.contactPhoneLabel || null,
    contactOfficeLabel: parsed.contactOfficeLabel || null,
    contactHoursLabel: parsed.contactHoursLabel || null,
    contactFormTitle: parsed.contactFormTitle || null,
    contactNameLabel: parsed.contactNameLabel || null,
    contactNamePlaceholder: parsed.contactNamePlaceholder || null,
    contactEmailFieldLabel: parsed.contactEmailFieldLabel || null,
    contactEmailPlaceholder: parsed.contactEmailPlaceholder || null,
    contactCompanyLabel: parsed.contactCompanyLabel || null,
    contactCompanyPlaceholder: parsed.contactCompanyPlaceholder || null,
    contactMessageLabel: parsed.contactMessageLabel || null,
    contactMessagePlaceholder: parsed.contactMessagePlaceholder || null,
    contactSubmitLabel: parsed.contactSubmitLabel || null,
    contactSendingLabel: parsed.contactSendingLabel || null,
    contactSuccessLabel: parsed.contactSuccessLabel || null,
    contactPrivacyText: parsed.contactPrivacyText || null,
    contactSubject: parsed.contactSubject || null,
    footerCompanyHeading: parsed.footerCompanyHeading || null,
    footerBrandsHeading: parsed.footerBrandsHeading || null,
    footerContactHeading: parsed.footerContactHeading || null,
    footerAboutLabel: parsed.footerAboutLabel || null,
    footerCopyrightSuffix: parsed.footerCopyrightSuffix || null,
    footerKvkkLabel: parsed.footerKvkkLabel || null,
    footerPrivacyLabel: parsed.footerPrivacyLabel || null,
    footerCookiesLabel: parsed.footerCookiesLabel || null,
  };

  await prisma.siteSetting.upsert({
    where: { id: "singleton" },
    update: data,
    create: { id: "singleton", ...data },
  });

  revalidatePath("/admin/settings");
  revalidatePath("/", "layout");
  return { ok: true };
}
